version: '3.8'

services:
  app:
    build: .
    container_name: intellect-server
    ports:
      - "1337:1337"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi_db
      - DATABASE_USERNAME=strapi_user
      - DATABASE_PASSWORD=strapi_password
      - DATABASE_SSL=false
      - JWT_SECRET=${JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
    depends_on:
      - db
    command: ["npm", "start"]
    volumes:
      - ./public/uploads:/app/public/uploads

  db:
    image: postgres:13
    container_name: intellect-db
    environment:
      - POSTGRES_DB=strapi_db
      - POSTGRES_USER=strapi_user
      - POSTGRES_PASSWORD=strapi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
